# Generated by Django 2.0.6 on 2018-10-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_mainfoodtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfoodtypes',
            name='childtypenames',
            field=models.CharField(max_length=255, verbose_name='子类型名称'),
        ),
        migrations.AlterField(
            model_name='mainfoodtypes',
            name='typename',
            field=models.CharField(max_length=255, verbose_name='类别名称'),
        ),
    ]
